// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2);
}

export function AddTransaction(arg1) {
  return window['go']['main']['App']['AddTransaction'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteBudget(arg1) {
  return window['go']['main']['App']['DeleteBudget'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function ExportEncryptedSharedData() {
  return window['go']['main']['App']['ExportEncryptedSharedData']();
}

export function GeneratePairingQR() {
  return window['go']['main']['App']['GeneratePairingQR']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBudgets(arg1) {
  return window['go']['main']['App']['GetBudgets'](arg1);
}

export function GetCoupleStatus() {
  return window['go']['main']['App']['GetCoupleStatus']();
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function ImportEncryptedSharedData(arg1) {
  return window['go']['main']['App']['ImportEncryptedSharedData'](arg1);
}

export function ProcessScannedQR(arg1) {
  return window['go']['main']['App']['ProcessScannedQR'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function SetBudget(arg1) {
  return window['go']['main']['App']['SetBudget'](arg1);
}

export function SetupMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['SetupMasterPassword'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function UpdateAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2, arg3);
}

export function UpdateAvatar(arg1) {
  return window['go']['main']['App']['UpdateAvatar'](arg1);
}

export function UpdateTransaction(arg1) {
  return window['go']['main']['App']['UpdateTransaction'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}
