// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAccount(arg1:string,arg2:number):Promise<models.Account>;

export function AddTransaction(arg1:models.Transaction):Promise<models.Transaction>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteBudget(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function ExportBackup():Promise<string>;

export function ExportEncryptedSharedData():Promise<string>;

export function GeneratePairingQR():Promise<string>;

export function GetAccounts():Promise<Array<models.Account>>;

export function GetAppVersion():Promise<string>;

export function GetBudgets(arg1:string):Promise<Array<models.Budget>>;

export function GetCoupleStatus():Promise<Record<string, any>>;

export function GetTransactions(arg1:Record<string, any>):Promise<Array<models.Transaction>>;

export function GetUser():Promise<models.User>;

export function ImportEncryptedSharedData(arg1:string):Promise<void>;

export function ProcessScannedQR(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function SetBudget(arg1:models.Budget):Promise<models.Budget>;

export function SetupMasterPassword(arg1:string,arg2:boolean):Promise<void>;

export function Shutdown():Promise<void>;

export function UpdateAccount(arg1:number,arg2:string,arg3:number):Promise<void>;

export function UpdateAvatar(arg1:string):Promise<void>;

export function UpdateTransaction(arg1:models.Transaction):Promise<void>;

export function UpdateUser(arg1:models.User):Promise<void>;
